logo: "/images/Tom1.jpg" # your photo (or logo) here
title: Tom Hopper # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Co-Director at MHP's Center for Housing Data
  <a href ="www.mhp.net/data">Check out our work</a>
  <br><br>
  <a href="www.linkedin.com/in/tom-hopper-1221166">View My LinkedIn Profile</a> 
    <br><br>
  <a href="https://twitter.com/Data_Hopper">Follow me on Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
