title: Tom Hopper # your name (or website title) here
logo: "/images/Tom1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Working at the intersection of data science and public policy
  <br><br>
  Co-Director at MHP's Center for Housing Data
  <br><br>
  <a href="www.linkedin.com/in/tom-hopper-1221166">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics:  # your Google Analytics tracking ID here
